
version: "3.3"
services:
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./docker/zookeeper/data:/data
      - ./docker/zookeeper/datalog:/datalog
    networks:
      myovernate:
    restart: always

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - ./docker/kafka/data:/var/lib/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      myovernate:
    restart: always

networks:
  myovernate:
    driver: overlay
    attachable: true