
version: "3.3"
services:
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./docker/zookeeper/data:/data
      - ./docker/zookeeper/datalog:/datalog
    restart: always

  kafka:
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    build:
      context: ./
      dockerfile: kafka/dockerfile_kafka
    privileged: true