FROM centos:7
MAINTAINER CFMC\gtamanov <gtamanov@cfmc.ru>
#LABEL Remarks="postgres  repmgr  pgpool"

ARG node_id

# for centos systemd
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# install services
USER root:root
RUN \
yum install java-1.8.0-openjdk.x86_64 -y&&\
yum clean all;

# Creating a User for Kafka
USER root:root
RUN \
adduser "kafka" &&\
echo "kafka" | passwd "kafka" --stdin &&\
usermod -aG wheel kafka ;

# Downloading and Extracting the Kafka Binaries
USER kafka:kafka
RUN \
mkdir ~/Downloads &&\
curl "https://downloads.apache.org/kafka/2.5.0/kafka_2.12-2.5.0.tgz" -o ~/Downloads/kafka.tgz &&\
mkdir ~/kafka && cd ~/kafka &&\
tar -xvzf ~/Downloads/kafka.tgz --strip 1;

# Configuring the Kafka Server
USER kafka:kafka
RUN \
echo "delete.topic.enable = true">>~/kafka/config/server.properties;

# Creating Systemd Unit Files and Starting the Kafka Server
USER root:root
RUN \
ls /etc &&\
echo "[Unit]">>/etc/systemd/system/kafka.service &&\
echo "Requires=network.target remote-fs.target">>/etc/systemd/system/kafka.service &&\
echo "After=network.target remote-fs.target">>/etc/systemd/system/kafka.service &&\
echo "[Service]">>/etc/systemd/system/kafka.service &&\
echo "Type=simple">>/etc/systemd/system/kafka.service &&\
echo "User=kafka">>/etc/systemd/system/kafka.service &&\
echo "ExecStart=/bin/sh -c '/home/kafka/kafka/bin/kafka-server-start.sh /home/kafka/kafka/config/server.properties > /home/kafka/kafka/kafka.log 2>&1'">>/etc/systemd/system/kafka.service &&\
echo "ExecStop=/home/kafka/kafka/bin/kafka-server-stop.sh">>/etc/systemd/system/kafka.service &&\
echo "Restart=on-abnormal">>/etc/systemd/system/kafka.service &&\
echo "[Install]">>/etc/systemd/system/kafka.service &&\
echo "WantedBy=multi-user.target">>/etc/systemd/system/kafka.service ;

# Creating systemctl enable Kafka Server
USER root:root
RUN \
systemctl enable kafka;

USER root:root
ENTRYPOINT ["/usr/sbin/init"]
